[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[dependencies]
aoclib = { git = "https://github.com/coriolinus/aoclib.git" }
clap = { version = "4.5.23", features = ["derive"] }
color-eyre = "0.5.11"
parse-display = "0.10.0"
priority-queue = "2.1.1"
